### ISSUE TITLE
Change label from hactoberfest to hacktoberfest and hactoberfest2021 to hacktoberfest2021

### ISSUE THREAD

**Issue by pratham-0094** [manmeetkr19/free-online-courses#10]
'k' is missing in label of the project
@manmeetkr19 
see the about section in rightside of screenshot
![Screenshot (125)](https://user-images.githubusercontent.com/80022922/135578354-deb29181-5dce-4bfe-9a54-4aa1297e8767.png)

**Comment by manmeetkr19** [comment]
Corrected, Thanks
